// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOawlsvCMxrDlC8fV2oUnja_fd3bXd4gY',
    appId: '1:572669546401:web:7830430c557c6edb1845e0',
    messagingSenderId: '572669546401',
    projectId: 'lighthouse-2498c',
    authDomain: 'lighthouse-2498c.firebaseapp.com',
    storageBucket: 'lighthouse-2498c.firebasestorage.app',
    measurementId: 'G-NET6W8XQD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvCmKXiO6UvBtqdu6YSzqV-NbzyICXOHU',
    appId: '1:572669546401:android:87a083b14672d9e11845e0',
    messagingSenderId: '572669546401',
    projectId: 'lighthouse-2498c',
    storageBucket: 'lighthouse-2498c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6fz6mwY3kpHGrR9znWa_nCE2J1xXHj4s',
    appId: '1:572669546401:ios:2b78e4b698be7f6f1845e0',
    messagingSenderId: '572669546401',
    projectId: 'lighthouse-2498c',
    storageBucket: 'lighthouse-2498c.firebasestorage.app',
    iosBundleId: 'com.example.ligthouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOawlsvCMxrDlC8fV2oUnja_fd3bXd4gY',
    appId: '1:572669546401:web:9a4b0472ea8b59de1845e0',
    messagingSenderId: '572669546401',
    projectId: 'lighthouse-2498c',
    authDomain: 'lighthouse-2498c.firebaseapp.com',
    storageBucket: 'lighthouse-2498c.firebasestorage.app',
    measurementId: 'G-YX984K86B5',
  );
}
